apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "myapp" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selectorLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabel }}
    spec:
      containers:
      - name: {{ .Values.containerName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        {{ with .Values.service }}
        ports:
        - containerPort: {{ .port }}
        {{ end }}