image: "nginx:1.25"
replicaCount: 2
service:
  type: ClusterIP
  port: 8080
  annotations: {}
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
env:
  - name: ENV
    value: "production"
  - name: LOG_LEVEL
    value: "info"